# Generated by Django 5.2.16 on 2026-07-31 13:48

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitosymetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('hora', models.TimeField()),
                ('dias_semana', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
                ('activo', models.BooleanField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(db_column='habito_id', on_delete=django.db.models.deletion.PROTECT, related_name='recordatorios', to='habitosymetas.habito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recordatorios',
            },
        ),
    ]
