# Generated by Django 5.2.16 on 2026-07-31 13:48

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(null=True)),
                ('fecha_inicio', models.DateField()),
                ('frecuencia_tipo', models.TextField(choices=[('diaria', 'Diaria'), ('dias_especificos', 'Dias Especificos'), ('n_veces_por_periodo', 'N Veces Por Periodo')])),
                ('frecuencia_dias_semana', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=None)),
                ('frecuencia_veces', models.IntegerField(null=True)),
                ('frecuencia_periodo', models.TextField(null=True)),
                ('categoria', models.TextField(null=True)),
                ('estado', models.TextField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('eliminado', 'Eliminado')], default='activo')),
                ('eliminado_en', models.DateTimeField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='habitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habitos',
            },
        ),
        migrations.CreateModel(
            name='HabitoPausa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(db_column='habito_id', on_delete=django.db.models.deletion.PROTECT, related_name='pausas', to='habitosymetas.habito')),
            ],
            options={
                'db_table': 'habito_pausas',
            },
        ),
        migrations.CreateModel(
            name='MetaPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_objetivo', models.DateField()),
                ('estado', models.TextField(choices=[('en_progreso', 'En Progreso'), ('lograda', 'Lograda'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='en_progreso')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metas',
            },
        ),
        migrations.AddField(
            model_name='habito',
            name='meta',
            field=models.ForeignKey(db_column='meta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitos', to='habitosymetas.metapersonal'),
        ),
        migrations.AddConstraint(
            model_name='metapersonal',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['en_progreso', 'lograda', 'pausada', 'cancelada'])), name='metas_estado_check'),
        ),
        migrations.AddIndex(
            model_name='habito',
            index=models.Index(condition=models.Q(('eliminado_en__isnull', True)), fields=['usuario'], name='habitos_usuario_id_idx'),
        ),
        migrations.AddIndex(
            model_name='habito',
            index=models.Index(condition=models.Q(('meta__isnull', False)), fields=['meta'], name='habitos_meta_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='habito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frecuencia_tipo', 'dias_especificos'), _negated=True), ('frecuencia_dias_semana__isnull', False), _connector='OR'), name='frecuencia_dias_especificos_requiere_dias'),
        ),
        migrations.AddConstraint(
            model_name='habito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frecuencia_tipo', 'n_veces_por_periodo'), _negated=True), models.Q(('frecuencia_veces__isnull', False), ('frecuencia_periodo__isnull', False)), _connector='OR'), name='frecuencia_n_veces_requiere_campos'),
        ),
    ]
