# Generated by Django 5.2.16 on 2026-07-31 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitosymetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionComunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('estado_moderacion', models.TextField(choices=[('visible', 'Visible'), ('en_revision', 'En Revision'), ('oculto', 'Oculto'), ('eliminado', 'Eliminado')], default='visible')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(null=True)),
                ('habito', models.ForeignKey(db_column='habito_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='habitosymetas.habito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publicaciones_comunidad',
            },
        ),
        migrations.CreateModel(
            name='ComentarioComunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('eliminado_en', models.DateTimeField(null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='comunidad.publicacioncomunidad')),
            ],
            options={
                'db_table': 'comentarios_comunidad',
            },
        ),
        migrations.CreateModel(
            name='ReaccionComunidad',
            fields=[
                ('pk', models.CompositePrimaryKey('publicacion', 'usuario', blank=True, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='reacciones', to='comunidad.publicacioncomunidad')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='reacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reacciones_comunidad',
            },
        ),
        migrations.CreateModel(
            name='ReporteComunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField(choices=[('spam', 'Spam'), ('acoso', 'Acoso'), ('inapropiado', 'Inapropiado'), ('otro', 'Otro')])),
                ('detalle', models.TextField(null=True)),
                ('estado', models.TextField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(null=True)),
                ('publicacion', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='comunidad.publicacioncomunidad')),
                ('reportante', models.ForeignKey(db_column='reportante_id', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(db_column='resuelto_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes_comunidad',
            },
        ),
        migrations.AddIndex(
            model_name='publicacioncomunidad',
            index=models.Index(condition=models.Q(('eliminado_en__isnull', True)), fields=['-creado_en'], name='publicaciones_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacioncomunidad',
            index=models.Index(fields=['usuario', '-creado_en'], name='publicaciones_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacioncomunidad',
            index=models.Index(condition=models.Q(('eliminado_en__isnull', True)), fields=['estado_moderacion', '-creado_en'], name='publicaciones_visibilidad_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicacioncomunidad',
            constraint=models.CheckConstraint(condition=models.Q(('contenido__trim__length__range', (1, 1000))), name='publicaciones_comunidad_contenido_check'),
        ),
        migrations.AddIndex(
            model_name='comentariocomunidad',
            index=models.Index(condition=models.Q(('eliminado_en__isnull', True)), fields=['publicacion', 'creado_en'], name='comentarios_publicacion_idx'),
        ),
        migrations.AddConstraint(
            model_name='comentariocomunidad',
            constraint=models.CheckConstraint(condition=models.Q(('contenido__trim__length__range', (1, 500))), name='comentarios_comunidad_contenido_check'),
        ),
        migrations.AddIndex(
            model_name='reportecomunidad',
            index=models.Index(fields=['estado', 'creado_en'], name='reportes_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportecomunidad',
            constraint=models.UniqueConstraint(fields=('publicacion', 'reportante'), name='reportes_comunidad_unico_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='reportecomunidad',
            constraint=models.CheckConstraint(condition=models.Q(('detalle__isnull', True), ('detalle__length__lte', 500), _connector='OR'), name='reportes_comunidad_detalle_limite'),
        ),
    ]
