# Generated by Django 5.2.16 on 2026-07-31 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitosymetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHabito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_local', models.DateField()),
                ('estado', models.TextField(choices=[('hecho', 'Hecho'), ('parcial', 'Parcial'), ('omitido', 'Omitido')])),
                ('nota', models.TextField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('habito', models.ForeignKey(db_column='habito_id', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='habitosymetas.habito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registros_habito',
                'constraints': [models.UniqueConstraint(fields=('habito', 'usuario', 'fecha_local'), name='registros_habito_clave_natural'), models.CheckConstraint(condition=models.Q(('estado__in', ['hecho', 'parcial', 'omitido'])), name='registros_habito_estado_check')],
            },
        ),
    ]
