# Generated by Django 5.2.16 on 2026-07-31 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInspiracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.TextField(choices=[('articulo', 'Articulo'), ('video', 'Video'), ('audio', 'Audio')])),
                ('titulo', models.TextField()),
                ('resumen', models.TextField()),
                ('url', models.TextField()),
                ('imagen_url', models.TextField(null=True)),
                ('autor', models.TextField()),
                ('destacado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contenidos_inspiracion',
                'indexes': [models.Index(fields=['publicado', '-destacado', '-creado_en'], name='inspiracion_listado_idx'), models.Index(fields=['tipo', 'publicado', '-creado_en'], name='inspiracion_tipo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('titulo__trim__length__range', (1, 180))), name='contenidos_inspiracion_titulo_check'), models.CheckConstraint(condition=models.Q(('resumen__trim__length__range', (1, 500))), name='contenidos_inspiracion_resumen_check'), models.CheckConstraint(condition=models.Q(('url__trim__length__range', (1, 2048))), name='contenidos_inspiracion_url_check'), models.CheckConstraint(condition=models.Q(('autor__trim__length__range', (1, 180))), name='contenidos_inspiracion_autor_check')],
            },
        ),
    ]
