# Generated by Django 5.2.16 on 2026-07-31 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitosymetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RachaHabito',
            fields=[
                ('pk', models.CompositePrimaryKey('habito', 'usuario', blank=True, editable=False, primary_key=True, serialize=False)),
                ('racha_actual', models.IntegerField(default=0)),
                ('racha_mas_larga', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('habito', models.ForeignKey(db_column='habito_id', on_delete=django.db.models.deletion.PROTECT, related_name='rachas', to='habitosymetas.habito')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='rachas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rachas_habito',
                'constraints': [models.CheckConstraint(condition=models.Q(('racha_actual__gte', 0), ('racha_mas_larga__gte', 0)), name='rachas_habito_contadores_no_negativos'), models.CheckConstraint(condition=models.Q(('racha_actual__lte', models.F('racha_mas_larga'))), name='rachas_habito_actual_no_supera_mas_larga')],
            },
        ),
    ]
