# Generated by Django 5.2.16 on 2026-07-31 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAdministrativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.TextField()),
                ('razon', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(db_column='objetivo_id', on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_administrativa',
                'indexes': [models.Index(fields=['objetivo', '-creado_en'], name='auditoria_objetivo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('razon__trim__length__range', (1, 500))), name='auditoria_administrativa_razon_check')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdministrativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('estado', models.TextField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente')),
                ('razon_decision', models.TextField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_en', models.DateTimeField(null=True)),
                ('revisado_por', models.ForeignKey(db_column='revisado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_administrativas',
                'indexes': [models.Index(fields=['estado', '-creado_en'], name='solicitudes_estado_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('motivo__trim__length__range', (1, 500))), name='solicitudes_administrativas_motivo_check'), models.CheckConstraint(condition=models.Q(('razon_decision__isnull', True), ('razon_decision__trim__length__range', (1, 500)), _connector='OR'), name='solicitudes_administrativas_razon_check'), models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('usuario',), name='solicitudes_admin_pendiente_usuario_unica')],
            },
        ),
    ]
