# Generated by Django 5.2.16 on 2026-07-31 13:48

import apps.identidad.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(db_column='password_hash')),
                ('rol', models.TextField(choices=[('regular', 'Regular'), ('admin', 'Admin')], default='regular')),
                ('estado', models.TextField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo')),
                ('consentimiento_aceptado_en', models.DateTimeField()),
                ('consentimiento_version', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='usuarios_email_unique')],
            },
            managers=[
                ('objects', apps.identidad.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'constraints': [models.UniqueConstraint(condition=models.Q(('used_at__isnull', True)), fields=('usuario',), name='one_active_reset_token_per_user')],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objetivo_general', models.TextField(null=True)),
                ('zona_horaria', models.TextField(default='UTC')),
                ('tts_habilitado', models.BooleanField(default=False)),
                ('tamano_texto', models.TextField(choices=[('normal', 'Normal'), ('grande', 'Grande'), ('extra_grande', 'Extra Grande')], default='normal')),
                ('contraste_alto', models.BooleanField(default=False)),
                ('notif_habilitadas', models.BooleanField(default=True)),
                ('resumen_progreso_habilitado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
                'constraints': [models.CheckConstraint(condition=models.Q(('tamano_texto__in', ['normal', 'grande', 'extra_grande'])), name='perfiles_tamano_texto_check')],
            },
        ),
    ]
